const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .use(express.static(path.join(__dirname, 'Homepage')))
  .use(express.static(path.join(__dirname, 'SpaceAdventure_Web')))
  .use(express.static(path.join(__dirname, 'BreakOut')))
  .use(express.static(path.join(__dirname, 'DreamAdventure')))
  .use(express.static(path.join(__dirname, 'DegreeShow')))
  .use(express.static(path.join(__dirname, 'Industry')))
  .use(express.static(path.join(__dirname, 'Gallery')))
  .use(express.static(path.join(__dirname, 'ArgonAssault')))
  .use(express.static(path.join(__dirname, '2D_RogueLike')))
  .use(express.static(path.join(__dirname, 'SpaceShooter')))
  .use(express.static(path.join(__dirname, 'RealmRush')))
  .get('/', (req, res) => res.sendFile('index.html', { root: __dirname + "/Homepage/" } ))
  .get('/SpaceAdventure', (req, res) => res.sendFile('index.html', { root: __dirname + "/SpaceAdventure_Web/" } ))
  .get('/BreakOut', (req, res) => res.sendFile('index.html', { root: __dirname + "/BreakOut/" } ))
  .get('/DreamAdventure', (req, res) => res.sendFile('index.html', { root: __dirname + "/DreamAdventure/" } ))
  .get('/DegreeShow', (req, res) => res.sendFile('degree_show.html', { root: __dirname + "/DegreeShow/" } ))
  .get('/Tessellation', (req, res) => res.sendFile('tessellation.html', { root: __dirname + "/DegreeShow/" } ))
  .get('/Industry/LiDL', (req, res) => res.sendFile('index.html', { root: __dirname + "/Industry/LiDL/" } ))
  .get('/Industry/SnickersBar', (req, res) => res.sendFile('index.html', { root: __dirname + "/Industry/Snickers bar/" } ))
  .get('/Industry/PacManGameplay', (req, res) => res.sendFile('index.html', { root: __dirname + "/Industry/PAC-MAN Gameplay/" } ))
  .get('/Industry/Mi5', (req, res) => res.sendFile('index.html', { root: __dirname + "/Industry/Mi5/" } ))
  .get('/Industry/ViacomSpark', (req, res) => res.sendFile('index.html', { root: __dirname + "/Industry/Viacom_Spark/" } ))
  .get('/Industry/Tropicana', (req, res) => res.sendFile('index.html', { root: __dirname + "/Industry/Tropicana/" } ))
  .get('/Gallery/2015InternShow', (req, res) => res.sendFile('index.html', { root: __dirname + "/Gallery/2015 Intern Show/" } ))
  .get('/Gallery/2016ArtSciShow', (req, res) => res.sendFile('index.html', { root: __dirname + "/Gallery/2016 ArtSci Show/" } ))
  .get('/Gallery/2016InternShow-MathematicSelf-Portrait', (req, res) => res.sendFile('index.html', { root: __dirname + "/Gallery/2016 InternShow-Mathematic Self-Portrait/" } ))
  .get('/Gallery/2017DegreeShow', (req, res) => res.sendFile('index.html', { root: __dirname + "/Gallery/2017 Degree Show/" } ))
  .get('/Gallery/2016PerformanceArtAtTateBritain', (req, res) => res.sendFile('index.html', { root: __dirname + "/Gallery/2016 Performance Art at Tate Britain/" } ))
  .get('/Gallery/2016Auction', (req, res) => res.sendFile('index.html', { root: __dirname + "/Gallery/2016 Auction/" } ))
  .get('/Gallery/FreelancePosterForZenWashoku', (req, res) => res.sendFile('index.html', { root: __dirname + "/Gallery/Freelance Poster for Zen Washoku/" } ))
  .get('/ArgonAssault', (req, res) => res.sendFile('index.html', { root: __dirname + "/ArgonAssault/" } ))
  .get('/2D_RogueLike', (req, res) => res.sendFile('index.html', { root: __dirname + "/2D_RogueLike/" } ))
  .get('/SpaceShooter', (req, res) => res.sendFile('index.html', { root: __dirname + "/SpaceShooter/" } ))
  .get('/RealmRush', (req, res) => res.sendFile('index.html', { root: __dirname + "/RealmRush/" } ))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
