const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .use(express.static(path.join(__dirname, 'Homepage')))
  .use(express.static(path.join(__dirname, 'SpaceAdventure_Web')))
  .use(express.static(path.join(__dirname, 'BreakOut')))
  .use(express.static(path.join(__dirname, 'DegreeShow')))
  .get('/', (req, res) => res.sendFile('index.html', { root: __dirname + "/Homepage/" } ))
  .get('/SpaceAdventure', (req, res) => res.sendFile('index.html', { root: __dirname + "/SpaceAdventure_Web/" } ))
  .get('/BreakOut', (req, res) => res.sendFile('index.html', { root: __dirname + "/BreakOut/" } ))
  .get('/DegreeShow', (req, res) => res.sendFile('degree_show.html', { root: __dirname + "/DegreeShow/" } ))
  .get('/Tessellation', (req, res) => res.sendFile('tessellation.html', { root: __dirname + "/DegreeShow/" } ))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
